### ISSUE TITLE
Integrate LangSmith Prompt SDK for better management, version control, and tracking of prompts.

### ISSUE THREAD

**Issue by nickjfrench** [langgenius/dify#10433]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

LangSmith has great functionality to test Prompts within it's platform based off traces from Dify. I'd love to be able to take the prompt I've been version tracking in LangSmith and automatically use it in Dify and viceversa. 
E.g. I update it on LangSmith, Dify uses it straight away in the next user call.
This would allow me to better track all prompts I'm using within the Dify platform.

LangSmith has an SDK api for push and pulling of prompts within their system. 
https://docs.smith.langchain.com/prompt_engineering/how_to_guides/prompts/manage_prompts_programatically  

### 2. Additional context or comments

Maybe to integrate this within Dify, some version of LangSmiths prompt library would be useful that has syncing capabilities with LangSmith. 

Also I don't think it's worth competing LangSmith on this feature, but instead integrating with it. 

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by ZhouhaoJiang** [comment]
@nickjfrench Hello, thank you for your suggestion. However, Dify is already integrated with LLM operations platforms such as Langfuse and Langsmith to expand its third-party capabilities. I reviewed Langsmith’s documentation on prompt engineering, but it doesn’t align with our current needs or development direction. Dify is compatible with various models, and integrating third-party prompt engineering features would not be consistent with our product vision. Dify itself already supports custom prompts, which provides the flexibility we need.
