### ISSUE TITLE
Intergrate SearXNG the meta search engine

### ISSUE THREAD

**Issue by wizd** [langgenius/dify#3193]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing?

We are searching for a search engine with good privacy protection. That's SearXNG.

### 2. Describe the feature you'd like to see

SearXNG is a meta search engine. https://github.com/searxng/searxng

### 3. How will this feature improve your workflow or experience?

To provide better search results than Google/Bing.

### 5. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by Yeuoly** [comment]
Just feel free to contribute anything :)

**Comment by crazywoola** [comment]
https://github.com/langgenius/dify/pull/3363
