### ISSUE TITLE
导入数据集时报错weaviate.exceptions.UnexpectedStatusCodeException: Meta endpoint! Unexpected status code: 404, with response body: {'detail': 'Not Found'}

### ISSUE THREAD

**Issue by HuQi1120** [langgenius/dify#3216]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Provide a description of requested docs changes

我修改了weaviate端口映射，然后上传数据集报错weaviate.exceptions.UnexpectedStatusCodeException: Meta endpoint! Unexpected status code: 404, with response body: {'detail': 'Not Found'}，请问是什么原因
weaviate中的apikey需要自己配置吗

**Comment by HuQi1120** [comment]
请问怎么更新WEAVIATE_ENDPOINT这个呢

**Comment by HuQi1120** [comment]
我更新了好像还是不可以
