### ISSUE TITLE
Invalid variable not giving checklist error

### ISSUE THREAD

**Issue by AndyMik90** [langgenius/dify#4607]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.8

### Cloud or Self Hosted

Cloud, Self Hosted (Docker), Self Hosted (Source)

### Steps to reproduce

![CleanShot 2024-05-23 at 08 21 30](https://github.com/langgenius/dify/assets/119136210/5a080cfe-08b3-4c00-903b-88960f187833)

if a variable in nodes are invalid, it doesn't trigger warnings in the checklist.

### ✔️ Expected Behavior

Warning on invalid variable

### ❌ Actual Behavior

Can publish and run workflows/chatflows with invalid variables set.
