### ISSUE TITLE
Enable users to edit <meta> tags for enhanced SEO customization.

### ISSUE THREAD

**Issue by lvjiajjjlzy** [langgenius/dify#5509]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

I hope to make the search engine discover the chat interface and add an entry for each chat to allow the addition of <meta> tags

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
Hello Do you mean allow editing the shared application?

**Comment by lvjiajjjlzy** [comment]
This is to make it accessible to more people through search engines, and the agent made by some people can really help more people.



---- Replied Message ----
| From | ***@***.***> |
| Date | 06/23/2024 08:51 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [langgenius/dify] Enable users to edit <meta> tags for enhanced SEO customization. (Issue #5509) |

Hello Do you mean allow editing the shared application?
