### ISSUE TITLE
[BUG]I got error "Meta endpoint! Unexpected status code: 503, with response body: None." when I upgrade to Version 0.6.12-fix1

### ISSUE THREAD

**Issue by haodaohong** [langgenius/dify#5893]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

Version 0.6.12-fix1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

after upgrade to Version 0.6.12-fix1 (only updated all URLs and port), then I try to do files embedding,  got this error "Meta endpoint! Unexpected status code: 503, with response body: None." .

<img width="867" alt="image" src="https://github.com/langgenius/dify/assets/1121928/04fb3c95-a4b3-4e4a-82b4-f5b18ea19f1b">

and also cannot ask question successfully
<img width="840" alt="image" src="https://github.com/langgenius/dify/assets/1121928/89e4875b-c01e-4ba6-85f6-a50ca9d9f62b">

### ✔️ Expected Behavior

can success do embedding， and can ask question

### ❌ Actual Behavior

error "Meta endpoint! Unexpected status code: 503, with response body: None."

**Comment by crazywoola** [comment]
It seems something wrong with the embedding services, please provide the container logs of worker and api. It's mostly due to the network connection issue between your server and embedding service, especially when you are using cohere rerank. Please make sure you have setup a VPN properly as well.

**Comment by haodaohong** [comment]
this is the error log as below, pls help to check, thanks a lot~

`api-1  | [2024-07-02 17:31:22 +0000] [23] [INFO] Starting gunicorn 22.0.0
api-1  | [2024-07-02 17:31:22 +0000] [23] [INFO] Listening at: http://0.0.0.0:5001 (23)
api-1  | [2024-07-02 17:31:22 +0000] [23] [INFO] Using worker: gevent
api-1  | [2024-07-02 17:31:22 +0000] [38] [INFO] Booting worker with pid: 38
api-1  | 2024-07-03 03:39:06,791.791 INFO [Dummy-1] [_client.py:1026] - HTTP Request: POST https://azscoai0001.openai.azure.com/openai/deployments/gpt-35-turbo-16k/chat/completions?api-version=2024-02-15-preview "HTTP/1.1 200 OK"
api-1  | 2024-07-03 03:39:15,825.825 INFO [Dummy-2] [_client.py:1026] - HTTP Request: POST https://azscoai0001.openai.azure.com/openai/deployments/whisper/audio/transcriptions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
api-1  | 2024-07-03 03:39:24,401.401 INFO [Dummy-3] [_client.py:1026] - HTTP Request: POST https://azscoai0001.openai.azure.com/openai/deployments/text-embedding-ada-002/embeddings?api-version=2024-04-01-preview "HTTP/1.1 200 OK"
api-1  | 2024-07-03 03:39:34,792.792 INFO [ThreadPoolExecutor-4_0] [_client.py:1026] - HTTP Request: POST https://azscoai0001.openai.azure.com/openai/deployments/tts-hd/audio/speech?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
api-1  | 2024-07-03 03:41:07,331.331 ERROR [Thread-7 (_generate_worker)] [app_generator.py:214] - Unknown Error when generating
api-1  | Traceback (most recent call last):
api-1  |   File "/app/api/core/app/apps/chat/app_generator.py", line 193, in _generate_worker
api-1  |     runner.run(
api-1  |   File "/app/api/core/app/apps/chat/app_runner.py", line 159, in run
api-1  |     context = dataset_retrieval.retrieve(
api-1  |   File "/app/api/core/rag/retrieval/dataset_retrieval.py", line 125, in retrieve
api-1  |     all_documents = self.single_retrieve(
api-1  |   File "/app/api/core/rag/retrieval/dataset_retrieval.py", line 271, in single_retrieve
api-1  |     results = RetrievalService.retrieve(
api-1  |   File "/app/api/core/rag/datasource/retrieval_service.py", line 87, in retrieve
api-1  |     raise Exception(exception_message)
api-1  | Exception: Meta endpoint! Unexpected status code: 503, with response body: None.
api-1  | 2024-07-03 03:41:07,338.338 ERROR [Dummy-6] [base_app_generate_response_converter.py:128] - Meta endpoint! Unexpected status code: 503, with response body: None.`

**Comment by crazywoola** [comment]
It seems a network issue on their side. See docs of 503 error here. https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/503

**Comment by haodaohong** [comment]
The issue has been resolved, but the cause is that docker could not pull at the beginning, so the relevant proxy config were used for docker, and then these proxy config affected the program to run, after deleting proxy config can ran successfully

**Comment by hi-noikiy** [comment]
> The issue has been resolved, but the cause is that docker could not pull at the beginning, so the relevant proxy config were used for docker, and then these proxy config affected the program to run, after deleting proxy config can ran successfully

请问你是怎么解决的？我现在是对添加到知识库里的文档索引的时候出现的问题

**Comment by he-ding** [comment]
The issue has been resolved. The reason for my problem was that my deployment environment is within the company's intranet, so I used a proxy. This caused the internal communication within Docker to be routed through the proxy to the internet. Specifically, the request to http://weaviate:8080/v1/meta was sent to the internet instead of being resolved locally, which prevented the knowledge base from being created. Hope this helps.
