### ISSUE TITLE
node title is overflow in checklist 

### ISSUE THREAD

**Issue by aixgeek** [langgenius/dify#5900]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.11

### Cloud or Self Hosted

Cloud, Self Hosted (Docker), Self Hosted (Source)

### Steps to reproduce

node title is overflow in checklist 

### ✔️ Expected Behavior

node title is  truncate in checklist 

### ❌ Actual Behavior

node title is overflow in checklist 
![image](https://github.com/langgenius/dify/assets/9697715/b4562d5c-28c4-48f2-9eec-d52def4a9f49)
![image](https://github.com/langgenius/dify/assets/9697715/fcfdc2eb-756b-48cf-b8d4-468d2f689769)
