### ISSUE TITLE
 Improve Configuration Usage Experience

### ISSUE THREAD

**Issue by laipz8200** [langgenius/dify#5937]
Currently, we have implemented a configuration based on Pydantic. However, we read the configuration through `Flask.config` or environment variables, which prevents us from utilizing Pydantic’s type system.

I have the following refactoring plan:

1. Create a singleton `DifyConfig`
2. Use this singleton to replace all logic that currently retrieves values from `current_app.config` ~~and environment variables~~
3. Modify any existing mock cases that might be affected

Since this refactoring involves a lot of code, we hope to complete it in multiple stages. If you're interested in helping us with this task, please leave a message here.🙏

Refactoring isn't too difficult, and even those who are not yet familiar with Dify can join in. If you're unsure about how to proceed, you can refer to #6025 and #5938.

Don't be shy, come and get involved!

## Current progress

- [x] `api/core/extension` #6025 
- [x] `api/core/model_runtime` #6025 
- [x] `api/models` #6394
- [x] `api/core/workflow` #6394
- [x] `api/core/tools` #6394
- [x] `api/core/rag` #6410
- [x] `api/core/file` #6747
- [x] `api/core/moderation` #6747
- [x] `api/core/app` #6747
- [x] `api/controllers/console` #6485
- [x] `api/controllers/inner_api` #6237
- [x] `api/controllers/service_api` #6237
- [x] `api/controllers/web` #6237
- [x] `api/scheduler` #6237
- [x] `api/services` #6203 
- [x] `api/tasks` #6203 
- [x] others #6750

**Comment by laipz8200** [comment]
Since this refactoring involves a lot of code, we hope to complete it in multiple stages. If you're interested in helping us with this task, please leave a message here.🙏

Refactoring isn't too difficult, and even those who are not yet familiar with Dify can join in. If you're unsure about how to proceed, you can refer to #5938.

Don't be shy, come and get involved!

**Comment by Poorandy** [comment]
I'm in. Just let me know if there's anything I can do.

**Comment by laipz8200** [comment]
Hi @Poorandy! Thank you for your response. Could you please check the directories `api/models`, `api/core/tools`, and `api/core/workflow`? Please modify the parts where `current_app.config` is used. 

You need to read our [Contribution Guide](https://github.com/langgenius/dify/blob/main/CONTRIBUTING.md) first. Once you are done, please open a pull request and refer to this issue.

**Comment by VickyGuo0907** [comment]
I want to contribute to this code refactoring. Please count me in. Let me know which directories I should work on.

**Comment by laipz8200** [comment]
Hi, @VickyGuo0907! Thank you for your reply. I've marked some directories for you, please check them. Have fun!

**Comment by Tian-Hun** [comment]
I would like to contribute to this issue. Please assign me some files or directories to work on.

**Comment by laipz8200** [comment]
Hi, @Tian-Hun! Thank you for your reply. I've marked some directories for you, please check them. Have fun!

**Comment by laipz8200** [comment]
@Poorandy @VickyGuo0907

Hi! Any updates on this?

**Comment by VickyGuo0907** [comment]
> @Poorandy @VickyGuo0907
> 
> Hi! Any updates on this?

Hi @laipz8200 , sorry I just saw this and will work on it.

**Comment by morugu** [comment]
Hi @laipz8200
I'd like to work on the `api/controllers/console` directory for this refactoring task. 
I'm excited to help improve Dify.

**Comment by laipz8200** [comment]
@morugu Have fun!

**Comment by laipz8200** [comment]
Hi @VickyGuo0907, are you still working on this issue?

**Comment by VickyGuo0907** [comment]
> Hi @VickyGuo0907, are you still working on this issue?

Hi @ laipz8200, those folders you assigned me have already implemented these changes.

**Comment by laipz8200** [comment]
@VickyGuo0907 It is not implemented yet, like [this line](https://github.com/langgenius/dify/blob/6ef401a9f0b557a37838f6cfd0446f2e97bd5b1f/api/core/app/apps/base_app_queue_manager.py#L51). Are you still interested in completing it?

**Comment by VickyGuo0907** [comment]
Hi @laipz8200 sorry about the confusion early. I submitted a pull request https://github.com/langgenius/dify/pull/6747, Please review it. any issue please let me know.  Thanks!

**Comment by laipz8200** [comment]
Just to let you know, we have completed this work. Thanks to every contributor.
