### ISSUE TITLE
Add app information using api access /meta

### ISSUE THREAD

**Issue by avasquezkudaw** [langgenius/dify#6490]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

Is it possible for the /meta endpoint to include additional application information, such as the ID, name, and description?

![Meta](https://github.com/user-attachments/assets/d08fabbd-5ec4-49dd-9cf2-8306321721aa)

### 2. Additional context or comments

Currently, according to the documentation, it only responds with icons, but it would be necessary for it to provide at least the name and description information.

### 3. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
This sounds good to me.

**Comment by avasquezkudaw** [comment]
Excellent, thank you very much for your response. 
Anyway, it would be ideal if the /info endpoint is included in the Api Access documentation. 

Regards.

**Comment by crazywoola** [comment]
Will do that later.
