### ISSUE TITLE
weaviate.exceptions.UnexpectedStatusCodeException: Meta endpoint! Unexpected status code: 401, with response body

### ISSUE THREAD

**Issue by muckthaa-ss** [langgenius/dify#6689]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.15

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce
```
[2024-07-25 09:40:20,394: INFO/MainProcess] Task tasks.document_indexing_task.document_indexing_task[2610a4be-cb9e-4134-89d9-f1ee0674b00b] received
[2024-07-25 09:40:20,394: INFO/MainProcess] Start process document: 95bdbcb0-b5e7-4c6a-951a-ee35b0571c27
[2024-07-25 09:41:35,300: ERROR/MainProcess] consume document failed
Traceback (most recent call last):
  File "C:\Users\hrith\OneDrive\Documents\dify_try\dify\api\core\indexing_runner.py", line 76, in run
    self._load(
  File "C:\Users\hrith\OneDrive\Documents\dify_try\dify\api\core\indexing_runner.py", line 689, in _load
    tokens += future.result()
  File "C:\Users\hrith\anaconda3\envs\dify_try\lib\concurrent\futures\_base.py", line 458, in result
    return self.__get_result()
  File "C:\Users\hrith\anaconda3\envs\dify_try\lib\concurrent\futures\_base.py", line 403, in __get_result
    raise self._exception
  File "C:\Users\hrith\anaconda3\envs\dify_try\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\hrith\OneDrive\Documents\dify_try\dify\api\core\indexing_runner.py", line 742, in _process_chunk
    index_processor.load(dataset, chunk_documents, with_keywords=False)
  File "C:\Users\hrith\OneDrive\Documents\dify_try\dify\api\core\rag\index_processor\processor\paragraph_index_processor.py", line 59, in load
    vector = Vector(dataset)
  File "C:\Users\hrith\OneDrive\Documents\dify_try\dify\api\core\rag\datasource\vdb\vector_factory.py", line 37, in __init__
    self._vector_processor = self._init_vector()
  File "C:\Users\hrith\OneDrive\Documents\dify_try\dify\api\core\rag\datasource\vdb\vector_factory.py", line 48, in _init_vector
    return vector_factory_cls().init_vector(self._dataset, self._attributes, self._embeddings)
  File "C:\Users\hrith\OneDrive\Documents\dify_try\dify\api\core\rag\datasource\vdb\weaviate\weaviate_vector.py", line 282, in init_vector
    return WeaviateVector(
  File "C:\Users\hrith\OneDrive\Documents\dify_try\dify\api\core\rag\datasource\vdb\weaviate\weaviate_vector.py", line 36, in __init__
    self._client = self._init_client(config)
  File "C:\Users\hrith\OneDrive\Documents\dify_try\dify\api\core\rag\datasource\vdb\weaviate\weaviate_vector.py", line 45, in _init_client
    client = weaviate.Client(
  File "C:\Users\hrith\anaconda3\envs\dify_try\lib\site-packages\weaviate\client.py", line 150, in __init__
    self._connection = Connection(
  File "C:\Users\hrith\anaconda3\envs\dify_try\lib\site-packages\weaviate\connect\connection.py", line 654, in __init__
    self._server_version = self.get_meta()["version"]
  File "C:\Users\hrith\anaconda3\envs\dify_try\lib\site-packages\weaviate\connect\connection.py", line 678, in get_meta
    raise UnexpectedStatusCodeException("Meta endpoint", response)
weaviate.exceptions.UnexpectedStatusCodeException: Meta endpoint! Unexpected status code: 401, with response body: {'code': 401, 'message': 'oidc auth is not configured, please try another auth scheme or set up weaviate with OIDC configured'}.
[2024-07-25 09:41:35,300: INFO/MainProcess] Processed dataset: ef2b0d8f-a569-4fee-a4e4-1ab709edb16e latency: 74.90517309999996
[2024-07-25 09:41:35,300: INFO/MainProcess] Task tasks.document_indexing_task.document_indexing_task[2610a4be-cb9e-4134-89d9-f1ee0674b00b] succeeded in 74.90600000000268s: None
```
![image (1)](https://github.com/user-attachments/assets/007594a6-1535-4635-95a9-c6dd5b653fd3)

### ✔️ Expected Behavior

to create chunks list in knownlege

### ❌ Actual Behavior

not working

**Comment by crazywoola** [comment]
> @dosu I have deployed dify locally from source code and never used docker at all. So How can I proceed? Also I have setup PostgreSQL, Redis and Weaviate locally.

If you don't run docker at all.

```
# ------------------------------
# Environment Variables for weaviate Service
# ------------------------------
WEAVIATE_QUERY_DEFAULTS_LIMIT=25
WEAVIATE_AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED=true
WEAVIATE_DEFAULT_VECTORIZER_MODULE=none
WEAVIATE_CLUSTER_HOSTNAME=node1
WEAVIATE_AUTHENTICATION_APIKEY_ENABLED=true
WEAVIATE_AUTHENTICATION_APIKEY_ALLOWED_KEYS=WVF5YThaHlkYwhGUSmCRgsX3tD5ngdN8pkih
WEAVIATE_AUTHENTICATION_APIKEY_USERS=hello@dify.ai
WEAVIATE_AUTHORIZATION_ADMINLIST_ENABLED=true
WEAVIATE_AUTHORIZATION_ADMINLIST_USERS=hello@dify.ai
```

These variables are important to the setup as the bot suggests.
